# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import reverse_pb2 as reverse__pb2


class ReverseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReverseString = channel.unary_unary(
                '/reverse.ReverseService/ReverseString',
                request_serializer=reverse__pb2.ReverseRequest.SerializeToString,
                response_deserializer=reverse__pb2.ReverseResponse.FromString,
                )


class ReverseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReverseString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReverseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReverseString': grpc.unary_unary_rpc_method_handler(
                    servicer.ReverseString,
                    request_deserializer=reverse__pb2.ReverseRequest.FromString,
                    response_serializer=reverse__pb2.ReverseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reverse.ReverseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReverseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReverseString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reverse.ReverseService/ReverseString',
            reverse__pb2.ReverseRequest.SerializeToString,
            reverse__pb2.ReverseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
