# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import social_pb2 as social__pb2


class SocialStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMessageStream = channel.stream_stream(
                '/social.Social/GetMessageStream',
                request_serializer=social__pb2.MessageRequest.SerializeToString,
                response_deserializer=social__pb2.Message.FromString,
                )


class SocialServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMessageStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SocialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMessageStream': grpc.stream_stream_rpc_method_handler(
                    servicer.GetMessageStream,
                    request_deserializer=social__pb2.MessageRequest.FromString,
                    response_serializer=social__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'social.Social', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Social(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMessageStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/social.Social/GetMessageStream',
            social__pb2.MessageRequest.SerializeToString,
            social__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
