# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reverse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reverse.proto',
  package='reverse',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rreverse.proto\x12\x07reverse\"\x1e\n\x0eReverseRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"(\n\x0fReverseResponse\x12\x15\n\rreversed_text\x18\x01 \x01(\t2V\n\x0eReverseService\x12\x44\n\rReverseString\x12\x17.reverse.ReverseRequest\x1a\x18.reverse.ReverseResponse\"\x00\x62\x06proto3'
)




_REVERSEREQUEST = _descriptor.Descriptor(
  name='ReverseRequest',
  full_name='reverse.ReverseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='reverse.ReverseRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=56,
)


_REVERSERESPONSE = _descriptor.Descriptor(
  name='ReverseResponse',
  full_name='reverse.ReverseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reversed_text', full_name='reverse.ReverseResponse.reversed_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['ReverseRequest'] = _REVERSEREQUEST
DESCRIPTOR.message_types_by_name['ReverseResponse'] = _REVERSERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReverseRequest = _reflection.GeneratedProtocolMessageType('ReverseRequest', (_message.Message,), {
  'DESCRIPTOR' : _REVERSEREQUEST,
  '__module__' : 'reverse_pb2'
  # @@protoc_insertion_point(class_scope:reverse.ReverseRequest)
  })
_sym_db.RegisterMessage(ReverseRequest)

ReverseResponse = _reflection.GeneratedProtocolMessageType('ReverseResponse', (_message.Message,), {
  'DESCRIPTOR' : _REVERSERESPONSE,
  '__module__' : 'reverse_pb2'
  # @@protoc_insertion_point(class_scope:reverse.ReverseResponse)
  })
_sym_db.RegisterMessage(ReverseResponse)



_REVERSESERVICE = _descriptor.ServiceDescriptor(
  name='ReverseService',
  full_name='reverse.ReverseService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=186,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReverseString',
    full_name='reverse.ReverseService.ReverseString',
    index=0,
    containing_service=None,
    input_type=_REVERSEREQUEST,
    output_type=_REVERSERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REVERSESERVICE)

DESCRIPTOR.services_by_name['ReverseService'] = _REVERSESERVICE

# @@protoc_insertion_point(module_scope)
